import { getStateByName } from "@/data/usStates";
import type { BillOfSaleFormValues } from "@/types/billOfSale";
import { formatDate, sanitizeFilePart } from "@/lib/utils";
import {
  addField,
  addHeader,
  addParagraph,
  addSectionTitle,
  addSignatureLines,
  createDoc,
  dateForFilename
} from "./helpers";

function usd(amount: number | undefined) {
  if (!amount || Number.isNaN(amount)) return "$0";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2
  }).format(amount);
}

export function generateBillOfSalePdf(data: BillOfSaleFormValues) {
  const state = getStateByName(data.state);
  const doc = createDoc("Vehicle bill of sale");
  addHeader(doc, "Vehicle bill of sale");

  let y = 122;
  y = addSectionTitle(doc, "Sale details", y);
  y = addField(doc, "State", data.state, y);
  y = addField(doc, "Sale date", formatDate(data.saleDate), y);
  y = addField(doc, "Sale price", usd(data.salePrice), y);
  y = addField(doc, "Payment method", data.paymentMethod, y);

  y = addSectionTitle(doc, "Seller", y + 6);
  y = addField(doc, "Name", data.sellerName, y);
  y = addField(doc, "Address", data.sellerAddress, y);
  y = addField(doc, "Phone/email", data.sellerContact, y);

  y = addSectionTitle(doc, "Buyer", y + 6);
  y = addField(doc, "Name", data.buyerName, y);
  y = addField(doc, "Address", data.buyerAddress, y);
  y = addField(doc, "Phone/email", data.buyerContact, y);

  y = addSectionTitle(doc, "Vehicle", y + 6);
  y = addField(doc, "Year/make/model", `${data.vehicleYear} ${data.vehicleMake} ${data.vehicleModel}`, y);
  y = addField(doc, "Body type", data.bodyType, y);
  y = addField(doc, "Color", data.color, y);
  y = addField(doc, "VIN", data.vin.toUpperCase(), y);
  y = addField(doc, "License plate", data.licensePlate, y);
  y = addField(doc, "Odometer", `${data.odometer.toLocaleString()} miles`, y);

  y = addSectionTitle(doc, "Disclosure and terms", y + 6);
  y = addParagraph(
    doc,
    `Odometer disclosure: The seller states that the odometer reading is ${data.odometer.toLocaleString()} miles to the best of the seller's knowledge.`
  , y);

  if (data.asIs) {
    y = addParagraph(
      doc,
      "As-is clause: The vehicle is sold as-is with no warranties, express or implied, except where prohibited by law."
    , y);
  }

  y = addParagraph(
    doc,
    state?.note ??
      "Check your state motor vehicle requirements before using this template."
  , y);
  y = addParagraph(
    doc,
    "Legal disclaimer: This document is a general template. Check your local DMV or legal authority before use."
  , y);

  y = addSignatureLines(doc, ["Seller signature", "Buyer signature"], y + 10);
  addParagraph(
    doc,
    "Generated by DocuGen. Your data was used in the browser to create this PDF and is not stored by DocuGen.",
    y
  );

  const statePart = sanitizeFilePart(data.state || "state");
  const date = dateForFilename(data.saleDate);
  doc.save(`vehicle-bill-of-sale-${statePart}-${date}.pdf`);
}
