import type { RentReceiptFormValues } from "@/types/rentReceipt";
import { formatCurrency } from "@/data/countries";
import { formatDate, sanitizeFilePart } from "@/lib/utils";
import {
  addField,
  addHeader,
  addParagraph,
  addSectionTitle,
  addSignatureLines,
  createDoc,
  dateForFilename
} from "./helpers";

export function generateRentReceiptPdf(data: RentReceiptFormValues) {
  const doc = createDoc("Rent receipt");
  addHeader(doc, "Rent receipt");

  let y = 122;
  y = addSectionTitle(doc, "Receipt details", y);
  y = addField(doc, "Receipt no.", data.receiptNo, y);
  y = addField(doc, "Country/region", `${data.country} - ${data.region}`, y);
  y = addField(doc, "Receipt date", formatDate(data.receiptDate), y);
  y = addField(
    doc,
    "Rent period",
    `${formatDate(data.rentStartDate)} to ${formatDate(data.rentEndDate)}`,
    y
  );
  y = addField(doc, "Payment method", data.paymentMethod, y);
  y = addField(doc, "Rent amount", formatCurrency(data.monthlyRent, data.country), y);
  y = addField(doc, "Receipt mode", data.receiptMode, y);

  y = addSectionTitle(doc, "Landlord", y + 6);
  y = addField(doc, "Name", data.landlordName, y);
  y = addField(doc, "Address", data.landlordAddress, y);
  if (data.country === "India") {
    y = addField(doc, "PAN", data.landlordPan?.toUpperCase(), y);
  }

  y = addSectionTitle(doc, "Tenant", y + 6);
  y = addField(doc, "Name", data.tenantName, y);
  y = addField(doc, "Address", data.tenantAddress, y);

  y = addSectionTitle(doc, "Property", y + 6);
  y = addField(doc, "Property address", data.propertyAddress, y);

  y = addParagraph(
    doc,
    `Received ${formatCurrency(data.monthlyRent, data.country)} from ${data.tenantName || "the tenant"} toward rent for the property listed above.`
  , y + 4);

  if (data.country === "India" && data.includeRevenueStampNote) {
    y = addParagraph(
      doc,
      "Revenue stamp note: Add a revenue stamp if required by your employer or local practice for cash payments."
    , y);
  }

  if (data.country === "India" && data.includeHraNote) {
    y = addParagraph(
      doc,
      "HRA note: Keep supporting proof such as lease agreement, payment proof, and landlord PAN where applicable."
    , y);
  }

  y = addSignatureLines(doc, ["Landlord signature", "Tenant acknowledgment"], y + 10);
  addParagraph(
    doc,
    "Generated by DocuGen. Your data was used in the browser to create this PDF and is not stored by DocuGen.",
    y
  );

  const tenant = sanitizeFilePart(data.tenantName || "tenant");
  const date = dateForFilename(data.receiptDate);
  doc.save(`rent-receipt-${tenant}-${date}.pdf`);
}
